[tox]
env_list = py{311,312,313,314}
min_version = 4.0

[testenv]
package = wheel
extras = test
install_command = python -I -m pip install --no-cache-dir {opts} {packages}
pass_env =
    R_HOME
    R_LIBS
    R_LIBS_SITE
    R_LIBS_USER
set_env =
    RPY2_CFFI_MODE = ABI
commands =
    pytest tests {posargs}
